[General]

# Enable Doorstop?
enabled = true

# Path to the assembly to load and execute
# NOTE: The entrypoint must be of format `static void Doorstop.Entrypoint.Start()`
target_assembly = BepInEx\core\BepInEx.Preloader.dll

# Enable execexe path substitution
subst_enabled = true

# execexe path substitution root
# If you're using BepInEx, it should be the path to BepInEx directory
subst_root = BepInEx\

# Enable patching avs2-core
# Allows using some characters in file names that are not supported by default
avspatch_enabled = true
