#!/usr/bin/env python3
"""
DeepL Translation Verifier for Chase Chase Jokers XUnity translation files.

Sends each Japanese key to DeepL, compares against the existing English value,
and opens a review UI where you can choose to keep the existing translation or
replace it with DeepL's — tags are preserved automatically.

Usage:
    1. Get a DeepL API key (free tier at https://www.deepl.com/pro-api):
       - Free: 500,000 characters/month
       - Add DEEPL_API_KEY to .env in the project root

    2. Install dependencies:
       pip install requests

    3. Run:
       python deepl_verify.py [--files gameplay.txt] [--limit N] [--threshold 0.4]
"""

import argparse
import csv
import os
import re
import sys
import time
from pathlib import Path

try:
    import requests
except ImportError:
    print("ERROR: 'requests' library not installed.")
    print("Run: pip install requests")
    sys.exit(1)


# ============================================================
# CONFIGURATION
# ============================================================

DEEPL_API_FREE    = "https://api-free.deepl.com/v2/translate"
DEEPL_API_PRO     = "https://api.deepl.com/v2/translate"
BATCH_SIZE        = 50
CACHE_FILE        = "deepl_cache.txt"
GLOSSARY_ID_FILE  = "deepl_glossary_id.txt"   # stores glossary_id<TAB>tsv_hash

TRANSLATION_FILES = [
    'abilities.txt', 'characters.txt', 'cosmetics.txt', 'gameplay.txt',
    'missions.txt', 'music.txt', 'skills.txt', 'system.txt', 'tutorial.txt',
    'titles.txt', '_AutoGeneratedTranslations.txt',
]

# DeepL translations whose text contains any of these words (case-insensitive)
# are automatically accepted without going through the review UI.
# Add terms here to expand the auto-accept list.
AUTO_ACCEPT_KEYWORDS = [
]


# ============================================================
# XUNITY PARSING HELPERS
# ============================================================

def unescape_xunity(s: str) -> str:
    return s.replace(r'\=', '=').replace(r'\\', '\\')


def strip_formatting_tags(s: str) -> str:
    s = re.sub(r'<sprite[^>]*>', '', s)
    s = re.sub(r'</?color[^>]*>', '', s)
    s = re.sub(r'</?size[^>]*>', '', s)
    s = re.sub(r'</?align[^>]*>', '', s)
    s = re.sub(r'<alpha[^>]*>', '', s)
    s = re.sub(r'<line-height[^>]*>', '', s)
    s = re.sub(r'<br/?>', ' ', s)
    s = s.replace(r'\n', ' ').replace(r'\r', ' ')
    return re.sub(r'\s+', ' ', s).strip()


def parse_entries(filepath: Path):
    """Yield (key, value, original_line, escaped_value) for each entry."""
    raw = filepath.read_bytes()
    if raw.startswith(b'\xef\xbb\xbf'):
        raw = raw[3:]
    text = raw.decode('utf-8')
    lines = text.split('\r\n') if '\r\n' in text else text.split('\n')
    for line in lines:
        if not line:
            continue
        m = re.search(r'(?<!\\)=', line)
        if not m:
            continue
        escaped_value = line[m.start() + 1:]
        key   = unescape_xunity(line[:m.start()])
        value = unescape_xunity(escaped_value)
        yield key, value, line, escaped_value


# ============================================================
# TAG RESTORATION
# ============================================================

def reapply_tags(escaped_value: str, stripped_value: str, deepl_en: str) -> str:
    """
    Substitute deepl_en into the tag structure of escaped_value, preserving
    color/sprite tags. Returns the new escaped value ready to write to file.
    """
    unescaped = unescape_xunity(escaped_value)

    # Simple case: plain text appears as a contiguous block inside the tags
    if stripped_value and stripped_value in unescaped:
        result = unescaped.replace(stripped_value, deepl_en, 1)
        return result.replace('=', r'\=')

    # Multi-segment case: text is split across several color tags.
    # Wrap the entire English text in any sprite prefix + the first color found.
    sprite_match = re.match(r'^(<sprite[^>]+>)', unescaped)
    first_color  = re.search(r'(<color=[^>]+>)', unescaped)
    prefix = sprite_match.group(1) if sprite_match else ''
    if first_color:
        result = f"{prefix}{first_color.group(1)}{deepl_en}</color>"
    else:
        result = f"{prefix}{deepl_en}"
    return result.replace('=', r'\=')


# ============================================================
# FILE PATCHING
# ============================================================

def apply_changes(input_dir: Path, changes: list[dict]):
    """
    Write chosen DeepL translations back to the source .txt files.
    Each change dict: {'fname', 'original_line', 'new_escaped_value'}
    """
    by_file: dict[str, list] = {}
    for ch in changes:
        by_file.setdefault(ch['fname'], []).append(ch)

    for fname, file_changes in by_file.items():
        p = Path(fname) if Path(fname).is_absolute() else input_dir / fname
        content = p.read_text(encoding='utf-8')

        # Backup original before touching it
        backup = p.with_suffix(p.suffix + '.bak')
        backup.write_text(content, encoding='utf-8')
        print(f"  Backup saved: {backup.name}")

        lines = content.splitlines(keepends=True)

        # Map original line (stripped of newline) -> replacement
        replacements = {}
        for ch in file_changes:
            orig = ch['original_line']
            m = re.search(r'(?<!\\)=', orig)
            if not m:
                continue
            new_line = orig[:m.start() + 1] + ch['new_escaped_value']
            if not new_line.endswith('\n'):
                new_line += '\n'
            replacements[orig.rstrip('\n\r')] = new_line

        new_lines = [
            replacements.get(ln.rstrip('\n\r'), ln)
            for ln in lines
        ]
        p.write_text(''.join(new_lines), encoding='utf-8')
        print(f"  Patched {len(file_changes)} entries in {p.name}")


# ============================================================
# DEEPL CLIENT
# ============================================================

class DeepLClient:
    def __init__(self, api_key: str):
        self.api_key  = api_key
        self.endpoint = DEEPL_API_FREE if api_key.endswith(":fx") else DEEPL_API_PRO
        self.session  = requests.Session()
        self.session.headers.update({"Authorization": f"DeepL-Auth-Key {api_key}"})
        self.characters_used = 0

    @property
    def glossary_base(self) -> str:
        return self.endpoint.replace("/translate", "/glossaries")

    # ── Glossary management ───────────────────────────────────

    def _tsv_entries(self, tsv_path: Path) -> str:
        """Return TSV content with comment/blank lines stripped and duplicates removed."""
        seen_keys: set[str] = set()
        lines = []
        for line in tsv_path.read_text(encoding='utf-8').splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith('#'):
                continue
            key = stripped.split('\t', 1)[0]
            if key in seen_keys:
                continue
            seen_keys.add(key)
            lines.append(stripped)
        return '\n'.join(lines)

    def _tsv_hash(self, tsv_path: Path) -> str:
        import hashlib
        return hashlib.md5(
            self._tsv_entries(tsv_path).encode('utf-8')
        ).hexdigest()

    def _load_glossary_id(self) -> tuple[str, str] | None:
        """Return (glossary_id, tsv_hash) from the local cache, or None."""
        p = Path.cwd() / GLOSSARY_ID_FILE
        if not p.exists():
            return None
        parts = p.read_text(encoding='utf-8').strip().split('\t')
        return (parts[0], parts[1]) if len(parts) == 2 else None

    def _save_glossary_id(self, glossary_id: str, tsv_hash: str):
        (Path.cwd() / GLOSSARY_ID_FILE).write_text(
            f"{glossary_id}\t{tsv_hash}", encoding='utf-8')

    def _delete_glossary(self, glossary_id: str):
        r = self.session.delete(f"{self.glossary_base}/{glossary_id}", timeout=10)
        if r.status_code not in (200, 204, 404):
            r.raise_for_status()

    def _create_glossary(self, tsv_path: Path) -> str:
        """Upload glossary to DeepL and return the new glossary_id."""
        entries = self._tsv_entries(tsv_path)
        r = self.session.post(
            self.glossary_base,
            headers={"Content-Type": "application/json"},
            json={
                "name":           "CCJ-Translation",
                "source_lang":    "JA",
                "target_lang":    "EN",
                "entries":        entries,
                "entries_format": "tsv",
            },
            timeout=30,
        )
        if not r.ok:
            raise RuntimeError(
                f"Glossary upload failed ({r.status_code}): {r.text[:400]}"
            )
        glossary_id = r.json()["glossary_id"]
        print(f"  Glossary uploaded → id: {glossary_id}")
        return glossary_id

    def ensure_glossary(self, tsv_path: Path, force: bool = False) -> str:
        """
        Return a valid DeepL glossary_id for tsv_path.
        Re-uploads when the TSV content has changed or force=True.
        """
        current_hash = self._tsv_hash(tsv_path)
        cached = self._load_glossary_id()

        if cached:
            gid, stored_hash = cached
            if not force and stored_hash == current_hash:
                print(f"  Glossary unchanged — reusing id: {gid}")
                return gid
            print("  Glossary force-refresh." if force else "  Glossary changed — re-uploading…")
            self._delete_glossary(gid)

        gid = self._create_glossary(tsv_path)
        self._save_glossary_id(gid, current_hash)
        return gid

    # ── Translation ───────────────────────────────────────────

    def translate_batch(self, texts: list[str],
                        glossary_id: str | None = None) -> list[str]:
        if not texts:
            return []
        params = {
            "source_lang": "JA",
            "target_lang": "EN-US",
            "preserve_formatting": "1",
            "tag_handling": "html",
        }
        if glossary_id:
            params["glossary_id"] = glossary_id
        data = [("text", t) for t in texts]
        try:
            r = self.session.post(self.endpoint, params=params, data=data, timeout=30)
            r.raise_for_status()
        except requests.HTTPError as e:
            if r.status_code == 456:
                raise RuntimeError("DeepL quota exceeded for the month.") from e
            if r.status_code == 403:
                raise RuntimeError("DeepL API key rejected (403). Check the key.") from e
            if r.status_code == 429:
                time.sleep(5)
                r = self.session.post(self.endpoint, params=params, data=data, timeout=30)
                r.raise_for_status()
        import html as _html
        result = r.json()
        self.characters_used += sum(len(t) for t in texts)
        return [_html.unescape(item["text"]) for item in result["translations"]]

    def get_usage(self) -> dict:
        usage_url = self.endpoint.replace("/translate", "/usage")
        r = self.session.get(usage_url, timeout=10)
        r.raise_for_status()
        return r.json()


# ============================================================
# CACHE
# ============================================================

def load_cache(cache_path: Path) -> dict:
    cache = {}
    if not cache_path.exists():
        return cache
    with open(cache_path, 'r', encoding='utf-8') as f:
        for line in f:
            parts = line.rstrip('\n').split('\t', 1)
            if len(parts) == 2:
                cache[parts[0]] = parts[1]
    return cache


def save_cache(cache: dict, cache_path: Path):
    with open(cache_path, 'w', encoding='utf-8') as f:
        for jp, en in cache.items():
            jp_s = jp.replace('\t', ' ').replace('\n', ' ')
            en_s = en.replace('\t', ' ').replace('\n', ' ')
            f.write(f"{jp_s}\t{en_s}\n")


# ============================================================
# SIMILARITY
# ============================================================

def tokenize(s: str) -> set[str]:
    s = re.sub(r"[^\w\s']", ' ', s.lower())
    return {w for w in s.split() if len(w) >= 2}


def jaccard(a: str, b: str) -> float:
    ta, tb = tokenize(a), tokenize(b)
    if not ta and not tb:
        return 1.0
    if not ta or not tb:
        return 0.0
    return len(ta & tb) / len(ta | tb)


# ============================================================
# REVIEW UI
# ============================================================

def launch_review_ui(flagged: list[dict], input_dir: Path):
    """
    One-at-a-time review UI.  Two buttons advance automatically;
    a preview shows the exact line that will be written to the file.
    """
    try:
        import tkinter as tk
        from tkinter import messagebox
    except ImportError:
        print("tkinter not available — skipping UI.  Use the TSV report instead.")
        return

    DARK   = "#1e1e1e"
    PANEL  = "#2d2d2d"
    ACCENT = "#569cd6"
    FG     = "#d4d4d4"
    GREEN  = "#4ec9b0"
    ORANGE = "#ce9178"
    DIM    = "#6a6a6a"

    root = tk.Tk()
    root.title("Translation Review")
    root.geometry("900x640")
    root.configure(bg=DARK)
    root.resizable(True, True)

    # ── State ─────────────────────────────────────────────────
    choices  = {}          # idx -> 'existing' | 'deepl'
    current  = [0]         # mutable pointer
    total    = len(flagged)

    # ── Helpers ───────────────────────────────────────────────
    def lbl(parent, text, color=DIM, size=9, bold=False):
        f = ("Consolas", size, "bold") if bold else ("Consolas", size)
        tk.Label(parent, text=text, bg=PANEL, fg=color, font=f,
                 anchor="w").pack(fill=tk.X, padx=12, pady=(8, 0))

    def txtbox(parent, height, color=FG):
        t = tk.Text(parent, height=height, bg="#141414", fg=color,
                    font=("Consolas", 10), wrap=tk.WORD, relief=tk.FLAT,
                    state=tk.DISABLED, padx=6, pady=4)
        t.pack(fill=tk.X, padx=12, pady=(2, 0))
        return t

    def set_txt(widget, text, color=None):
        widget.configure(state=tk.NORMAL)
        if color:
            widget.configure(fg=color)
        widget.delete("1.0", tk.END)
        widget.insert(tk.END, text)
        widget.configure(state=tk.DISABLED)

    # ── Header ────────────────────────────────────────────────
    header = tk.Frame(root, bg=DARK)
    header.pack(fill=tk.X, padx=12, pady=(10, 0))

    progress_lbl = tk.Label(header, text="", bg=DARK, fg=ACCENT,
                            font=("Consolas", 10, "bold"))
    progress_lbl.pack(side=tk.LEFT)

    file_lbl = tk.Label(header, text="", bg=DARK, fg=DIM,
                        font=("Consolas", 9))
    file_lbl.pack(side=tk.RIGHT)

    # Progress bar (canvas)
    bar_canvas = tk.Canvas(root, height=4, bg="#333333",
                           highlightthickness=0)
    bar_canvas.pack(fill=tk.X, padx=12, pady=(4, 0))
    bar_fill = bar_canvas.create_rectangle(0, 0, 0, 4, fill=ACCENT, width=0)

    def update_bar(idx):
        bar_canvas.update_idletasks()
        w = bar_canvas.winfo_width()
        x = int(w * (idx / total)) if total else 0
        bar_canvas.coords(bar_fill, 0, 0, x, 4)

    # ── Content panel ─────────────────────────────────────────
    panel = tk.Frame(root, bg=PANEL)
    panel.pack(fill=tk.BOTH, expand=True, padx=12, pady=8)

    lbl(panel, "JAPANESE",          ACCENT, bold=True)
    txt_jp  = txtbox(panel, 2)

    lbl(panel, "CURRENT TRANSLATION", ORANGE, bold=True)
    txt_cur = txtbox(panel, 2, ORANGE)

    lbl(panel, "DEEPL TRANSLATION",   GREEN,  bold=True)
    txt_dl  = txtbox(panel, 2, GREEN)

    lbl(panel, "PREVIEW  —  line as it will appear in the file", DIM)
    txt_pre = txtbox(panel, 3, FG)

    # ── Button row ────────────────────────────────────────────
    btn_row = tk.Frame(root, bg=DARK)
    btn_row.pack(fill=tk.X, padx=12, pady=(0, 10))

    BTN = dict(font=("Consolas", 12, "bold"), relief=tk.FLAT,
               cursor="hand2", padx=20, pady=10)

    btn_keep  = tk.Button(btn_row, text="◀  Keep existing",
                          bg="#3a2800", fg=ORANGE, **BTN)
    btn_deepl = tk.Button(btn_row, text="Use DeepL  ▶",
                          bg="#003a28", fg=GREEN,  **BTN)
    btn_keep .pack(side=tk.LEFT,  expand=True, fill=tk.X, padx=(0, 4))
    btn_deepl.pack(side=tk.RIGHT, expand=True, fill=tk.X, padx=(4, 0))

    # ── Summary / apply screen ────────────────────────────────
    def show_summary():
        # Destroy content and show summary
        for w in panel.winfo_children():
            w.destroy()
        for w in btn_row.winfo_children():
            w.destroy()
        header.pack_forget()
        bar_canvas.pack_forget()

        deepl_count = sum(1 for c in choices.values() if c == "deepl")
        tk.Label(panel, text="Review complete",
                 bg=PANEL, fg=ACCENT,
                 font=("Consolas", 14, "bold")).pack(pady=(30, 8))
        tk.Label(panel,
                 text=f"{deepl_count} entries will be replaced with DeepL translations\n"
                      f"{total - deepl_count} entries kept as existing",
                 bg=PANEL, fg=FG, font=("Consolas", 11)).pack(pady=8)

        def do_apply():
            to_patch = []
            for i, e in enumerate(flagged):
                if choices.get(i) == "deepl":
                    new_val = reapply_tags(
                        e['escaped_value'], e['value_stripped'], e['deepl_en'])
                    to_patch.append({
                        'fname':             e['fname'],
                        'original_line':     e['original_line'],
                        'new_escaped_value': new_val,
                    })
            if not to_patch:
                messagebox.showinfo("Nothing to do",
                                    "No entries were set to 'Use DeepL'.")
                return
            apply_changes(input_dir, to_patch)
            messagebox.showinfo("Done",
                f"Applied {len(to_patch)} changes.\nOriginal files backed up as .bak")
            root.destroy()

        tk.Button(panel, text="Apply Changes", bg=ACCENT, fg="#ffffff",
                  font=("Consolas", 12, "bold"), relief=tk.FLAT,
                  padx=24, pady=10, command=do_apply).pack(pady=16)
        tk.Button(panel, text="Cancel (no changes)", bg="#333333", fg=DIM,
                  font=("Consolas", 10), relief=tk.FLAT,
                  command=root.destroy).pack()

    # ── Load entry ────────────────────────────────────────────
    def load(idx):
        if idx >= total:
            show_summary()
            return
        e = flagged[idx]
        progress_lbl.config(text=f"Entry {idx + 1} of {total}")
        file_lbl.config(text=Path(e['fname']).name +
                        f"  ·  sim {e['similarity']:.2f}")
        update_bar(idx)

        set_txt(txt_jp,  e['key_stripped'])
        set_txt(txt_cur, e['value_stripped'], ORANGE)
        set_txt(txt_dl,  e['deepl_en'],       GREEN)

        # Preview: show the full .txt line for each option
        new_val      = reapply_tags(e['escaped_value'], e['value_stripped'], e['deepl_en'])
        orig_m       = re.search(r'(?<!\\)=', e['original_line'])
        key_part     = e['original_line'][:orig_m.end()] if orig_m else ""
        preview_line = key_part + new_val
        set_txt(txt_pre, preview_line, FG)

    def choose(decision):
        idx = current[0]
        choices[idx] = decision
        current[0]  += 1
        load(current[0])

    btn_keep .config(command=lambda: choose("existing"))
    btn_deepl.config(command=lambda: choose("deepl"))

    # Keyboard shortcuts
    root.bind("<Left>",  lambda _: choose("existing"))
    root.bind("<Right>", lambda _: choose("deepl"))

    load(0)
    root.mainloop()

    root.mainloop()


# ============================================================
# MAIN VERIFICATION FLOW
# ============================================================

def verify_files(
    input_dir: Path,
    output_path: Path,
    api_key: str,
    files: list[str],
    threshold: float,
    limit: int | None,
    skip_short: bool,
    skip_tagged_passthrough: bool,
    glossary_path: Path | None = None,
    refresh_glossary: bool = False,
) -> list[dict]:
    # Cache lives in the current working directory
    cache_path = Path.cwd() / CACHE_FILE
    cache = load_cache(cache_path)
    print(f"Loaded cache: {len(cache)} entries  ({cache_path})")

    client = DeepLClient(api_key)
    try:
        usage = client.get_usage()
        used  = usage.get("character_count", 0)
        cap   = usage.get("character_limit", 500_000)
        print(f"DeepL usage: {used:,} / {cap:,} chars ({100*used/max(cap,1):.1f}%)")
    except Exception as e:
        print(f"Warning: could not fetch usage: {e}")

    # Set up glossary if provided
    glossary_id: str | None = None
    if glossary_path and glossary_path.exists():
        print(f"Glossary: {glossary_path.name}")
        try:
            glossary_id = client.ensure_glossary(glossary_path, force=refresh_glossary)
        except Exception as e:
            print(f"Warning: could not set up glossary: {e}")

    # Collect entries
    # tuple: (fname, key, value, stripped_key, stripped_value, original_line, escaped_value)
    all_entries = []
    for fname in files:
        p = Path(fname) if Path(fname).is_absolute() else input_dir / fname
        if not p.exists():
            print(f"  SKIP (missing): {fname}")
            continue
        file_entries = list(parse_entries(p))
        if limit:
            file_entries = file_entries[:limit]
        for key, value, original_line, escaped_value in file_entries:
            if not re.search(r'[぀-ゟ゠-ヿ一-鿿]', key):
                continue
            stripped_key   = strip_formatting_tags(key)
            stripped_value = strip_formatting_tags(value)
            if skip_short and len(stripped_key) < 3:
                continue
            if skip_tagged_passthrough and re.search(
                    r'[぀-ゟ゠-ヿ一-鿿]', stripped_value):
                continue
            all_entries.append((fname, key, value, stripped_key,
                                stripped_value, original_line, escaped_value))

    print(f"\n{len(all_entries)} entries to verify across {len(files)} file(s)")

    # Translate uncached
    uncached = list(dict.fromkeys(
        e[3] for e in all_entries if e[3] not in cache
    ))
    est = sum(len(k) for k in uncached)
    print(f"Need to translate {len(uncached)} new strings (~{est:,} chars)")

    if uncached:
        if input(f"Proceed with DeepL calls? [y/N] ").strip().lower() != 'y':
            print("Aborted.")
            return []

    for i in range(0, len(uncached), BATCH_SIZE):
        batch = uncached[i:i + BATCH_SIZE]
        n_batches = (len(uncached) + BATCH_SIZE - 1) // BATCH_SIZE
        print(f"  Batch {i//BATCH_SIZE + 1}/{n_batches} ({len(batch)} strings)...",
              end='', flush=True)
        try:
            translations = client.translate_batch(batch, glossary_id=glossary_id)
            for jp, en in zip(batch, translations):
                cache[jp] = en
            print(" ✓")
        except Exception as e:
            print(f" ✗ ({e})")
            save_cache(cache, cache_path)
            raise
        save_cache(cache, cache_path)
        time.sleep(0.5)

    print(f"\nCache now has {len(cache)} entries")

    # Compare, auto-accept keyword matches, and collect flagged entries
    flagged: list[dict] = []
    auto_patch: list[dict] = []

    def _is_auto_accept(deepl_en: str) -> bool:
        low = deepl_en.lower()
        return any(kw in low for kw in AUTO_ACCEPT_KEYWORDS)

    print(f"\nWriting TSV report to {output_path}...")
    with open(output_path, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f, delimiter='\t', quoting=csv.QUOTE_MINIMAL)
        writer.writerow(["File", "Sim", "Japanese", "Current", "DeepL", "Auto-accepted"])
        for fname, key, value, sk, sv, orig_line, esc_val in all_entries:
            deepl_en = cache.get(sk)
            if not deepl_en:
                continue
            sim = jaccard(sv, deepl_en)
            if sim >= threshold:
                continue

            if _is_auto_accept(deepl_en):
                writer.writerow([fname, f"{sim:.2f}", sk, sv, deepl_en, "yes"])
                auto_patch.append({
                    'fname':             fname,
                    'original_line':     orig_line,
                    'new_escaped_value': reapply_tags(esc_val, sv, deepl_en),
                })
            else:
                writer.writerow([fname, f"{sim:.2f}", sk, sv, deepl_en, ""])
                flagged.append({
                    'fname':          fname,
                    'key_stripped':   sk,
                    'value_stripped': sv,
                    'escaped_value':  esc_val,
                    'deepl_en':       deepl_en,
                    'similarity':     sim,
                    'original_line':  orig_line,
                })

    if auto_patch:
        print(f"Auto-accepted {len(auto_patch)} entries (keyword match) — applying now…")
        apply_changes(input_dir, auto_patch)

    print(f"Flagged {len(flagged)} entries for manual review")
    print(f"DeepL chars used this session: {client.characters_used:,}")
    return flagged


# ============================================================
# CLI
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        description="Verify XUnity translations against DeepL.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--input-dir", type=Path,
        default=Path(__file__).parent.parent.parent / "BepInEx" / "Translation" / "en" / "Text",
        help="Directory containing the .txt translation files",
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).parent / "deepl_verification_report.tsv",
        help="Where to save the TSV divergence report",
    )
    parser.add_argument("--threshold",  type=float, default=0.4)
    parser.add_argument("--limit",      type=int,   default=None)
    parser.add_argument("--files",      nargs="+",  default=TRANSLATION_FILES)
    parser.add_argument("--include-short",       action="store_true")
    parser.add_argument("--include-passthrough", action="store_true")
    parser.add_argument("--no-ui", action="store_true",
                        help="Skip the review UI, just generate the TSV report.")
    parser.add_argument(
        "--glossary", type=Path,
        default=Path(__file__).parent / "deepl_glossary.tsv",
        help="Path to the glossary TSV file (default: deepl_glossary.tsv next to this script)",
    )
    parser.add_argument(
        "--refresh-glossary", action="store_true",
        help="Force re-upload of the glossary to DeepL, ignoring the cached ID.",
    )

    args = parser.parse_args()

    # Load .env from project root
    _env_file = Path(__file__).parent.parent.parent / ".env"
    if _env_file.exists():
        try:
            from dotenv import load_dotenv
            load_dotenv(_env_file, override=False)
        except ImportError:
            with open(_env_file, "r", encoding="utf-8") as _f:
                for _line in _f:
                    _line = _line.strip()
                    if not _line or _line.startswith("#") or "=" not in _line:
                        continue
                    _k, _, _v = _line.partition("=")
                    _k = _k.strip()
                    _v = _v.strip().strip('"').strip("'")
                    if _k and _k not in os.environ:
                        os.environ[_k] = _v

    api_key = os.environ.get("DEEPL_API_KEY", "").strip()
    if not api_key:
        print("ERROR: DEEPL_API_KEY not set.")
        print(f"Add it to {_env_file}:  DEEPL_API_KEY=\"your-key:fx\"")
        sys.exit(1)

    if not all(Path(f).is_absolute() for f in args.files):
        if not args.input_dir.exists():
            print(f"ERROR: input directory not found: {args.input_dir}")
            sys.exit(1)

    flagged = verify_files(
        input_dir=args.input_dir,
        output_path=args.output,
        api_key=api_key,
        files=args.files,
        threshold=args.threshold,
        limit=args.limit,
        skip_short=not args.include_short,
        glossary_path=args.glossary,
        refresh_glossary=args.refresh_glossary,
        skip_tagged_passthrough=not args.include_passthrough,
    )

    if flagged and not args.no_ui:
        print(f"\nLaunching review UI for {len(flagged)} flagged entries...")
        launch_review_ui(flagged, args.input_dir)
    elif flagged:
        print(f"\n{len(flagged)} entries flagged. See {args.output}")


if __name__ == "__main__":
    main()
